# Generated by Django 4.1 on 2023-06-19 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_date_post_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostSort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.CharField(choices=[('date_post', 'сначала старые посты'), ('-date_post', 'сначала новые посты')], default='-date_post', max_length=100, verbose_name='Сортировать')),
            ],
        ),
        migrations.RemoveField(
            model_name='comment',
            name='title',
        ),
    ]
