# Generated by Django 4.1 on 2023-06-20 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_post_count_alter_comment_author_alter_comment_post_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='count',
        ),
    ]
