# Generated by Django 4.1 on 2023-06-20 21:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_remove_post_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertising',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='static/img/service-6.jpg', upload_to='', verbose_name='Изображение')),
                ('title', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Заголовок')),
                ('url', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Заголовок')),
                ('date_post', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата')),
            ],
        ),
    ]
