# Generated by Django 4.1 on 2023-06-20 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_advertising'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertising',
            name='url',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Ссылка'),
        ),
    ]
