# Generated by Django 4.1 on 2023-06-20 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_advertising_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertising',
            options={'verbose_name': 'Реклама', 'verbose_name_plural': 'Реклама'},
        ),
    ]
