# Generated by Django 4.1 on 2023-06-20 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_advertising_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertising',
            name='company',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Организация'),
        ),
    ]
