# Generated by Django 4.1 on 2023-06-20 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_advertising_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertising',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Статус'),
        ),
    ]
