# Generated by Django 4.1 on 2023-06-21 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_advertising_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(default='', max_length=100, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(default='', max_length=100, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='postsort',
            name='items',
            field=models.CharField(choices=[('date_post', 'сначала старые посты'), ('-date_post', 'сначала новые посты')], default='-date_post', max_length=100, verbose_name=''),
        ),
    ]
